name: Sync Issues to Projects

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  sync-to-projects:
    runs-on: solinas
    steps:
      - name: Add Issue to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.tools.sap/orgs/cloud-curriculum/projects/1
          github-token: '${{ secrets.SYNC_TO_PROJECT }}'
      - name: Attempt to assign column
        run: |
          echo "itemId: ${{ steps.add-issue.outputs.itemId }}"
          echo ${{ secrets.SYNC_TO_PROJECT }} | gh auth login --with-token -h github.tools.sap -p https
          gh project item-edit --id ${{ steps.add-issue.outputs.itemId }} --field-id MDI2OlByb2plY3RWMlNpbmdsZVNlbGVjdEZpZWxkNTQwOQ== --project-id MDk6UHJvamVjdFYyNjE3 --single-select-option-id c22571b4
